// Top 10 decks "do meta" (arquétipos populares) como ponto de partida. Cada
// carta é buscada pelo nome na Pokémon TCG API ao carregar (em paralelo, com
// cache). As contagens somam ~60 e respeitam o limite de 4 cópias.
//
// `share` = participação aproximada no meta competitivo (Standard), usada para
// ordenar por popularidade e destacar o mais jogado. Fonte dos arquétipos:
// resultados de torneios agregados (LimitlessTCG).
export const META_SOURCE = {
  label: 'LimitlessTCG',
  url: 'https://limitlesstcg.com/decks',
};

export interface MetaDeckTemplate {
  id: string;
  name: string;
  share: number;
  cards: { query: string; count: number }[];
}

// Utilitário de sanidade: soma das cópias de um deck (deve ser 60).
export const templateSize = (t: MetaDeckTemplate): number =>
  t.cards.reduce((s, c) => s + c.count, 0);

export const META_DECKS: MetaDeckTemplate[] = [
  {
    // 16 Pokémon · 35 Treinadores · 9 Energia = 60
    id: 'charizard',
    name: '🔥 Charizard ex',
    share: 18,
    cards: [
      { query: 'Charizard ex', count: 3 },
      { query: 'Charmander', count: 4 },
      { query: 'Charmeleon', count: 2 },
      { query: 'Pidgey', count: 3 },
      { query: 'Pidgeot ex', count: 2 },
      { query: 'Manaphy', count: 1 },
      { query: 'Lumineon V', count: 1 },
      { query: "Professor's Research", count: 4 },
      { query: 'Iono', count: 3 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Arven', count: 4 },
      { query: 'Rare Candy', count: 4 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Buddy-Buddy Poffin', count: 4 },
      { query: 'Super Rod', count: 2 },
      { query: 'Counter Catcher', count: 2 },
      { query: 'Switch', count: 3 },
      { query: 'Fire Energy', count: 9 },
    ],
  },
  {
    // 18 Pokémon · 27 Treinadores · 15 Energia = 60
    id: 'gardevoir',
    name: '🔮 Gardevoir ex',
    share: 11,
    cards: [
      { query: 'Gardevoir ex', count: 3 },
      { query: 'Ralts', count: 4 },
      { query: 'Kirlia', count: 4 },
      { query: 'Zacian V', count: 1 },
      { query: 'Munkidori', count: 2 },
      { query: 'Mew ex', count: 1 },
      { query: 'Fezandipiti ex', count: 1 },
      { query: 'Radiant Greninja', count: 1 },
      { query: 'Manaphy', count: 1 },
      { query: "Professor's Research", count: 2 },
      { query: 'Iono', count: 3 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Arven', count: 3 },
      { query: 'Rare Candy', count: 4 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Level Ball', count: 3 },
      { query: 'Battle VIP Pass', count: 4 },
      { query: 'Super Rod', count: 1 },
      { query: 'Counter Catcher', count: 1 },
      { query: 'Psychic Energy', count: 15 },
    ],
  },
  {
    // 17 Pokémon · 23 Treinadores · 20 Energia = 60
    id: 'lugia',
    name: '🌀 Lugia VSTAR',
    share: 8,
    cards: [
      { query: 'Lugia VSTAR', count: 3 },
      { query: 'Lugia V', count: 3 },
      { query: 'Archeops', count: 4 },
      { query: 'Lumineon V', count: 2 },
      { query: 'Cinccino', count: 2 },
      { query: 'Minccino', count: 2 },
      { query: 'Radiant Greninja', count: 1 },
      { query: "Professor's Research", count: 3 },
      { query: 'Iono', count: 2 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Serena', count: 2 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Capacious Bucket', count: 3 },
      { query: 'Super Rod', count: 2 },
      { query: 'Double Turbo Energy', count: 4 },
      { query: 'Powerful Colorless Energy', count: 3 },
      { query: 'Water Energy', count: 7 },
      { query: 'Fire Energy', count: 4 },
      { query: 'Jet Energy', count: 2 },
      { query: 'Reversal Energy', count: 2 },
    ],
  },
  {
    // 12 Pokémon · 30 Treinadores · 18 Energia = 60
    id: 'miraidon',
    name: '⚡ Miraidon ex',
    share: 7,
    cards: [
      { query: 'Miraidon ex', count: 3 },
      { query: 'Pikachu ex', count: 2 },
      { query: 'Flaaffy', count: 2 },
      { query: 'Mareep', count: 2 },
      { query: 'Raikou V', count: 2 },
      { query: 'Squawkabilly ex', count: 1 },
      { query: "Professor's Research", count: 2 },
      { query: 'Iono', count: 3 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Arven', count: 2 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Electric Generator', count: 4 },
      { query: 'Battle VIP Pass', count: 4 },
      { query: 'Super Rod', count: 2 },
      { query: 'Switch Cart', count: 2 },
      { query: 'Lightning Energy', count: 20 },
    ],
  },
  {
    // 12 Pokémon · 33 Treinadores · 15 Energia = 60
    id: 'lostbox',
    name: '🌌 Lost Box',
    share: 7,
    cards: [
      { query: 'Comfey', count: 4 },
      { query: 'Sableye', count: 2 },
      { query: 'Cramorant', count: 2 },
      { query: 'Radiant Greninja', count: 1 },
      { query: 'Mew ex', count: 1 },
      { query: 'Raikou V', count: 1 },
      { query: 'Manaphy', count: 1 },
      { query: "Colress's Experiment", count: 4 },
      { query: 'Battle VIP Pass', count: 4 },
      { query: 'Nest Ball', count: 4 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Switch Cart', count: 2 },
      { query: 'Lost Vacuum', count: 2 },
      { query: 'Super Rod', count: 1 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Iono', count: 2 },
      { query: 'Counter Catcher', count: 2 },
      { query: 'Path to the Peak', count: 2 },
      { query: 'Water Energy', count: 7 },
      { query: 'Psychic Energy', count: 6 },
      { query: 'Lightning Energy', count: 5 },
      { query: 'Fighting Energy', count: 1 },
    ],
  },
  {
    // 12 Pokémon · 30 Treinadores · 18 Energia = 60
    id: 'gholdengo',
    name: '🪙 Gholdengo ex',
    share: 6,
    cards: [
      { query: 'Gholdengo ex', count: 3 },
      { query: 'Gimmighoul', count: 3 },
      { query: 'Bronzong', count: 2 },
      { query: 'Bronzor', count: 2 },
      { query: 'Fezandipiti ex', count: 1 },
      { query: 'Radiant Greninja', count: 1 },
      { query: "Professor's Research", count: 3 },
      { query: 'Iono', count: 3 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Arven', count: 4 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Great Ball', count: 2 },
      { query: 'Super Rod', count: 2 },
      { query: 'Counter Catcher', count: 2 },
      { query: 'Earthen Vessel', count: 3 },
      { query: 'Metal Energy', count: 20 },
    ],
  },
  {
    // 13 Pokémon · 32 Treinadores · 15 Energia = 60
    id: 'chienpao',
    name: '❄️ Chien-Pao ex',
    share: 6,
    cards: [
      { query: 'Chien-Pao ex', count: 3 },
      { query: 'Baxcalibur', count: 3 },
      { query: 'Frigibax', count: 4 },
      { query: 'Manaphy', count: 1 },
      { query: 'Radiant Greninja', count: 1 },
      { query: 'Lumineon V', count: 1 },
      { query: "Professor's Research", count: 3 },
      { query: 'Iono', count: 2 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Irida', count: 2 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Superior Energy Retrieval', count: 3 },
      { query: 'Super Rod', count: 2 },
      { query: 'Buddy-Buddy Poffin', count: 4 },
      { query: 'Earthen Vessel', count: 2 },
      { query: 'Water Energy', count: 20 },
    ],
  },
  {
    // 16 Pokémon · 25 Treinadores · 19 Energia = 60
    id: 'arceus',
    name: '🌟 Arceus VSTAR',
    share: 5,
    cards: [
      { query: 'Arceus VSTAR', count: 3 },
      { query: 'Arceus V', count: 4 },
      { query: 'Bidoof', count: 2 },
      { query: 'Bibarel', count: 2 },
      { query: 'Giratina VSTAR', count: 2 },
      { query: 'Giratina V', count: 2 },
      { query: 'Radiant Greninja', count: 1 },
      { query: "Professor's Research", count: 3 },
      { query: 'Iono', count: 2 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Arven', count: 2 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Super Rod', count: 2 },
      { query: 'Counter Catcher', count: 1 },
      { query: 'Earthen Vessel', count: 2 },
      { query: 'Double Turbo Energy', count: 4 },
      { query: 'Grass Energy', count: 12 },
      { query: 'Fire Energy', count: 4 },
      { query: 'Lightning Energy', count: 3 },
    ],
  },
  {
    // 9 Pokémon · 33 Treinadores · 18 Energia = 60
    id: 'roaringmoon',
    name: '🦖 Roaring Moon ex',
    share: 5,
    cards: [
      { query: 'Roaring Moon ex', count: 3 },
      { query: 'Squawkabilly ex', count: 1 },
      { query: 'Galarian Moltres', count: 1 },
      { query: 'Koraidon', count: 2 },
      { query: 'Radiant Greninja', count: 1 },
      { query: 'Fezandipiti ex', count: 1 },
      { query: "Professor's Research", count: 2 },
      { query: 'Iono', count: 3 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Arven', count: 2 },
      { query: 'Ultra Ball', count: 4 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Dark Patch', count: 4 },
      { query: 'Earthen Vessel', count: 3 },
      { query: 'Super Rod', count: 2 },
      { query: 'Counter Catcher', count: 2 },
      { query: 'Buddy-Buddy Poffin', count: 4 },
      { query: 'Darkness Energy', count: 20 },
    ],
  },
  {
    // 7 Pokémon · 49 Treinadores · 4 Energia = 60
    id: 'snorlax',
    name: '💤 Snorlax Stall',
    share: 3,
    cards: [
      { query: 'Snorlax', count: 4 },
      { query: 'Munchlax', count: 2 },
      { query: 'Klefki', count: 1 },
      { query: 'Pokémon Center Lady', count: 2 },
      { query: "Boss's Orders", count: 2 },
      { query: 'Iono', count: 3 },
      { query: "Professor's Research", count: 2 },
      { query: 'Pokégear 3.0', count: 4 },
      { query: 'Counter Catcher', count: 3 },
      { query: 'Great Ball', count: 4 },
      { query: 'Path to the Peak', count: 2 },
      { query: 'Cyllene', count: 2 },
      { query: 'Nest Ball', count: 3 },
      { query: 'Ultra Ball', count: 2 },
      { query: 'Lost Vacuum', count: 2 },
      { query: "Erika's Invitation", count: 2 },
      { query: 'Unfair Stamp', count: 1 },
      { query: 'Town Store', count: 2 },
      { query: 'Big Air Balloon', count: 2 },
      { query: 'Rescue Board', count: 2 },
      { query: 'Jamming Tower', count: 2 },
      { query: 'Judge', count: 1 },
      { query: 'Artazon', count: 2 },
      { query: 'Switch', count: 2 },
      { query: 'Grass Energy', count: 6 },
    ],
  },
];
